### ISSUE TITLE
Getting type error when upgrading to 2.0.0 to 3.0.1

### ISSUE THREAD

**Issue by DeepikaSharma5** [voximplant/react-native-foreground-service#54]
I was using 2.0.0 without any issue for SDK 30. But as now I have upgraded to SDK 31 the previous version doesen't work. So I tried to update the package to 3.0.1. But after upgrade, when I run the project I am getting an error as `TypeError: _reactNativeForegroundService.default.stopService is not a function. (In '_reactNativeForegroundService.default.stopService()', '_reactNativeForegroundService.default.stopService' is undefined)` and the app crashed.

I am using SDK 33, react-native 0.64.4

@akvakh @YuliaGrigorieva @aylarov @DmitryIvaneychik

**Comment by eisodev** [comment]
Review the docs again, they added getInstance() to the function call after v3.

Before:
`VIForegroundService.stopService();`

After:
`VIForegroundService.getInstance().stopService();`

**Comment by gauri-28** [comment]
Still getting same issue
###  _reactNativeForegroundService.default.stopService is not a function. (In '_reactNativeForegroundService.default.stopService()', '_reactNativeForegroundService.default.stopService' is ### undefined)

After using -> VIForegroundService.getInstance().stopService();
